#!/usr/bin/env bash
# regenerates go stubs for the agent from the shared proto contract.
# needs: Go. The Buf CLI version is pinned here and in CI; Rust stubs are
# generated by cargo build (build.rs).
set -euo pipefail

BUF_VERSION="v1.47.2"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "[proto] generating go stubs -> agent/gen"
cd "$ROOT/agent"
go run "github.com/bufbuild/buf/cmd/buf@${BUF_VERSION}" generate ../proto

echo "[proto] done. rust stubs are built automatically by 'cargo build' in master/."
